[project]
name = 'boom-shop'
description = 'Boom Shop - A decentralized marketplace'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.boom-market]
path = 'contracts/boom-market.clar'
clarity_version = 2
epoch = 2.5

[contracts.boom-nft]
path = 'contracts/boom-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.nft-trait]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.smart-shop-trait]
path = 'contracts/smart-shop-trait.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
